server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/urlshortener
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicTypeRegistry: TRACE

urlshortener:
  base-url: http://localhost:8080/api
  short-url-length: 6
  expiration-time: 30 # in days